### ISSUE TITLE
Error dell e5470 

### ISSUE THREAD

**Issue by kris0725pl** [lzhoang2801/Hardware-Sniffer#11]
hi, i got error when select option 6 for create efi.

> Traceback (most recent call last):
  File "C:\Users\Dell\Desktop\Dell e4570 Hackintosh\OpCore-Simplify-main\OpCore-Simplify-main\OpCore-Simplify.py", line 351, in <module>
    o.main()
    ~~~~~~^^
  File "C:\Users\Dell\Desktop\Dell e4570 Hackintosh\OpCore-Simplify-main\OpCore-Simplify-main\OpCore-Simplify.py", line 339, in main
    self.gathering_files(macos_version)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Dell\Desktop\Dell e4570 Hackintosh\OpCore-Simplify-main\OpCore-Simplify-main\OpCore-Simplify.py", line 38, in gathering_files
    self.o.gather_bootloader_kexts(self.k.kexts, macos_version)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dell\Desktop\Dell e4570 Hackintosh\OpCore-Simplify-main\OpCore-Simplify-main\Scripts\gathering_files.py", line 183, in gather_bootloader_kexts
    self.utils.extract_zip_file(zip_path)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\Dell\Desktop\Dell e4570 Hackintosh\OpCore-Simplify-main\OpCore-Simplify-main\Scripts\utils.py", line 114, in extract_zip_file
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
         ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python313\Lib\zipfile\__init__.py", line 1362, in __init__
    self.fp = io.open(file, filemode)
              ~~~~~~~^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Dell\\AppData\\Local\\Temp\\tmpbvu61lq_\\NullEthernet.zip'



my dell spec:
[HW Sniff.txt](https://github.com/user-attachments/files/18281129/HW.Sniff.txt)
![Dell e5470](https://github.com/user-attachments/assets/557dbcfd-25d8-4279-ba49-45ccd5fd0096)


What i m doing?

**Comment by lzhoang2801** [comment]
Duplicate of https://github.com/lzhoang2801/OpCore-Simplify/issues/81
