### ISSUE TITLE
Dump ACPI broken

### ISSUE THREAD

**Issue by arka003** [lzhoang2801/Hardware-Sniffer#2]
Dump ACPI tables doesn't work

I have python 3.13 installed

This is what I'm getting for the Dump ACPI Option:

Traceback (most recent call last):
  File "Hardware-Sniffer.py", line 181, in <module>
  File "Hardware-Sniffer.py", line 175, in main
  File "Hardware-Sniffer.py", line 75, in dump_acpi_tables
  File "Hardware-Sniffer.py", line 53, in check_acpidump
Exception: Could not get latest ACPI Binary Tools for Windows

**Comment by lzhoang2801** [comment]
Manually download Windows Binary Tools from [ACPICA](https://www.intel.com/content/www/us/en/developer/topic-technology/open/acpica/download.html), then copy the iasl.exe file into the Scripts folder and run it again to see the result

**Comment by lzhoang2801** [comment]
Fixed https://github.com/lzhoang2801/Hardware-Sniffer/commit/f1c1079e79f1782a11c047f742149d93fb9d9e07
