### ISSUE TITLE
Error during export

### ISSUE THREAD

**Issue by startergo** [lzhoang2801/Hardware-Sniffer#9]
```
####################################################################
#                        An Error Occurred                         #
####################################################################

Traceback (most recent call last):
  File "C:\Users\user\Downloads\OpCore-Simplify-main\OpCore-Simplify-main\OpCore-Simplify.py", line 349, in <module>
    o.main()
    ~~~~~~^^
  File "C:\Users\user\Downloads\OpCore-Simplify-main\OpCore-Simplify-main\OpCore-Simplify.py", line 307, in main
    hardware_report_path, hardware_report = self.select_hardware_report()
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\user\Downloads\OpCore-Simplify-main\OpCore-Simplify-main\OpCore-Simplify.py", line 82, in select_hardware_report
    data = self.u.read_file(path)
  File "C:\Users\user\Downloads\OpCore-Simplify-main\OpCore-Simplify-main\Scripts\utils.py", line 34, in read_file
    with open(file_path, "r" if file_extension == ".json" else "rb") as file_handle:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\user\\Downloads\\OpCore-Simplify-main\\OpCore-Simplify-main'




Press Enter to continue...
```

**Comment by startergo** [comment]
ran it in powershell7 and it worked.
